### ISSUE TITLE
Count number of dependencies in a type.

### ISSUE THREAD

**Issue by jyp** [omelkonian/agda2train#11]
It would be useful to know how "dependent" a type is. The reason is that one can expect that a type with more dependencies is more constrained than a type without. If a type is more constrained then it's more challenging and interesting to do lemma guessing for it. Some examples:

    | type                                     | dep. level | why                                |
    |------------------------------------------|------------|------------------------------------|
    | Nat -> Nat -> Nat                        | 0          | no occurence of free variable      |
    | (A : Set) -> A -> A                      | 2          | A occurs 2 times                   |
    | (n : Nat) -> Fin n -> Fin n -> Fin (2*n) | 3          | n occurs 3 times                   |
    | (n : Nat) -> Fin n -> Fin n -> Fin (n+n) | 4          | n occurs 4 times                   |
    | (A B : Set) -> (A -> B) -> A -> B        | 4          | A occurs 2 times, B occurs 2 times |
    | (a : Level) -> (A : Set a) -> A -> A     | 2          | level quantifications don't count  |

**Comment by omelkonian** [comment]
@jyp Could you take a look at the new [golden JSONs](https://github.com/omelkonian/agda2train/commit/9a4c7d15bd343f7bf1bed760f4a15e4310c71509), in particular [`Test.DependencyLevels`](https://github.com/omelkonian/agda2train/commit/9a4c7d15bd343f7bf1bed760f4a15e4310c71509#diff-455d5852389605f09c22a4913430a6fc3648ed32cb5cdc9dd91ba801290689db) to make sure this is implemented as expected?
